# Generated by Django 3.2.2 on 2021-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0003_remove_covid_per_etn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='nom_grupo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
